--[[
  Purpose: Shipped class defaults for HUNTER (pet bar uses base placement).
  Deps: ShadowUI addon table
  Public: populates ShadowUI.Defaults.classes.HUNTER
]]

local Addon = LibStub("AceAddon-3.0"):GetAddon("ShadowUI")
local act = Addon.Defaults.act

Addon.Defaults.classes.HUNTER = {
  layout = {},
  keybinds = {
    ["CLICK ShadowUIActionButton1:Keybind"] = "Q",
    ["CLICK ShadowUIActionButton2:Keybind"] = "E",
    ["CLICK ShadowUIActionButton3:Keybind"] = "R",
    ["CLICK ShadowUIActionButton4:Keybind"] = "F",
    ["CLICK ShadowUIActionButton5:Keybind"] = "T",
    ["CLICK ShadowUIActionButton6:Keybind"] = "G",
    ["CLICK ShadowUIActionButton7:Keybind"] = "C",
    ["CLICK ShadowUIActionButton8:Keybind"] = "V",
    ["CLICK ShadowUIActionButton9:Keybind"] = "B",
    ["CLICK ShadowUIActionButton10:Keybind"] = "X",
    ["CLICK ShadowUIActionButton11:Keybind"] = "Z",
    ["CLICK ShadowUIActionButton12:Keybind"] = "H",
    ["CLICK ShadowUIActionButton13:Keybind"] = "1",
    ["CLICK ShadowUIActionButton14:Keybind"] = "2",
    ["CLICK ShadowUIActionButton15:Keybind"] = "3",
    ["CLICK ShadowUIActionButton16:Keybind"] = "4",
    ["CLICK ShadowUIActionButton17:Keybind"] = "5",
    ["CLICK ShadowUIActionButton18:Keybind"] = "`",
    ["CLICK ShadowUIActionButton19:Keybind"] = "SHIFT-Q",
    ["CLICK ShadowUIActionButton20:Keybind"] = "SHIFT-E",
    ["CLICK ShadowUIActionButton21:Keybind"] = "SHIFT-R",
    ["CLICK ShadowUIActionButton22:Keybind"] = "SHIFT-F",
    ["CLICK ShadowUIActionButton23:Keybind"] = "SHIFT-T",
    ["CLICK ShadowUIActionButton24:Keybind"] = "N",
    ["CLICK ShadowUIActionButton25:Keybind"] = "SHIFT-G",
    ["CLICK ShadowUIActionButton26:Keybind"] = "SHIFT-C",
    ["CLICK ShadowUIActionButton27:Keybind"] = "SHIFT-V",
    ["CLICK ShadowUIActionButton28:Keybind"] = "SHIFT-B",
    ["CLICK ShadowUIActionButton29:Keybind"] = "SHIFT-X",
    ["CLICK ShadowUIActionButton30:Keybind"] = "SHIFT-Z",
    ["CLICK ShadowUIActionButton31:Keybind"] = "SHIFT-H",
    ["CLICK ShadowUIActionButton32:Keybind"] = "SHIFT-N",
    ["CLICK ShadowUIActionButton33:Keybind"] = "6",
    ["CLICK ShadowUIActionButton34:Keybind"] = "7",
    ["CLICK ShadowUIActionButton35:Keybind"] = "8",
    ["CLICK ShadowUIActionButton36:Keybind"] = "9",
    ["CLICK ShadowUIActionButton37:Keybind"] = "SHIFT-1",
    ["CLICK ShadowUIActionButton38:Keybind"] = "SHIFT-2",
    ["CLICK ShadowUIActionButton39:Keybind"] = "SHIFT-3",
    ["CLICK ShadowUIActionButton40:Keybind"] = "SHIFT-4",
    ["CLICK ShadowUIActionButton41:Keybind"] = "SHIFT-5",
    ["CLICK ShadowUIActionButton42:Keybind"] = "SHIFT-`",
    ["CLICK ShadowUIActionButton43:Keybind"] = "ALT-1",
    ["CLICK ShadowUIActionButton44:Keybind"] = "ALT-2",
    ["CLICK ShadowUIActionButton45:Keybind"] = "ALT-3",
    ["CLICK ShadowUIActionButton46:Keybind"] = "ALT-4",
    ["CLICK ShadowUIActionButton47:Keybind"] = "ALT-5",
    ["CLICK ShadowUIActionButton48:Keybind"] = "ALT-6",
    ["CLICK ShadowUIActionButton49:Keybind"] = "ALT-Q",
    ["CLICK ShadowUIActionButton50:Keybind"] = "ALT-E",
    ["CLICK ShadowUIActionButton51:Keybind"] = "ALT-R",
    ["CLICK ShadowUIActionButton52:Keybind"] = "ALT-F",
    ["CLICK ShadowUIActionButton53:Keybind"] = "ALT-T",
    ["CLICK ShadowUIActionButton54:Keybind"] = "ALT-G",
    ["CLICK ShadowUIActionButton55:Keybind"] = "ALT-C",
    ["CLICK ShadowUIActionButton56:Keybind"] = "ALT-V",
    ["CLICK ShadowUIActionButton57:Keybind"] = "ALT-B",
    ["CLICK ShadowUIActionButton58:Keybind"] = "ALT-X",
    ["CLICK ShadowUIActionButton59:Keybind"] = "ALT-Z",
    ["CLICK ShadowUIActionButton60:Keybind"] = "0",
    ["CLICK ShadowUIActionButton61:Keybind"] = "CTRL-Q",
    ["CLICK ShadowUIActionButton62:Keybind"] = "CTRL-E",
    ["CLICK ShadowUIActionButton63:Keybind"] = "CTRL-R",
    ["CLICK ShadowUIActionButton64:Keybind"] = "CTRL-F",
    ["CLICK ShadowUIActionButton65:Keybind"] = "CTRL-T",
    ["CLICK ShadowUIActionButton66:Keybind"] = "CTRL-G",
    ["CLICK ShadowUIActionButton67:Keybind"] = "CTRL-C",
    ["CLICK ShadowUIActionButton68:Keybind"] = "CTRL-V",
    ["CLICK ShadowUIActionButton69:Keybind"] = "CTRL-B",
    ["CLICK ShadowUIActionButton70:Keybind"] = "CTRL-1",
    ["CLICK ShadowUIActionButton71:Keybind"] = "CTRL-2",
    ["CLICK ShadowUIActionButton72:Keybind"] = "CTRL-3",
    ["CLICK ShadowUIActionButton73:Keybind"] = "BUTTON5",
    ["CLICK ShadowUIActionButton74:Keybind"] = "BUTTON4",
    ["CLICK ShadowUIActionButton75:Keybind"] = "BUTTON3",
    ["CLICK ShadowUIActionButton76:Keybind"] = "ALT-SHIFT-1",
    ["CLICK ShadowUIActionButton77:Keybind"] = "ALT-SHIFT-2",
    ["CLICK ShadowUIActionButton78:Keybind"] = "ALT-SHIFT-3",
    ["CLICK ShadowUIActionButton79:Keybind"] = "F1",
    ["CLICK ShadowUIActionButton80:Keybind"] = "ALT-SHIFT-Q",
    ["CLICK ShadowUIActionButton81:Keybind"] = "ALT-SHIFT-E",
    ["CLICK ShadowUIActionButton82:Keybind"] = "ALT-SHIFT-R",
    ["CLICK ShadowUIActionButton83:Keybind"] = "ALT-SHIFT-F",
    ["CLICK ShadowUIActionButton84:Keybind"] = "ALT-SHIFT-C",
  },
  actions = {
    [1] = act("h-aimed", "as", { match = "Aimed Shot" }),
    [2] = act("h-arcane", "arc", { match = "arc" }),
    [3] = act("h-multi", "multi", { match = "Multi-Shot" }),
    [4] = act("h-tranq", "tq", { match = "Tranquilizing Shot" }),
    [5] = act("h-rapid", "rapid", { match = "Rapid Fire" }),
    [7] = act("h-conc", "conc", { match = "Concussive Shot" }),
    [8] = act("h-aspect", "asp", { match = "asp" }),
    [9] = act("shared-t14", "t14", { match = "t14" }),
    [10] = act("h-trap", "ft", { match = "Freezing Trap" }),
    [11] = act("h-fd", "fd", { match = "Feign Death" }),
    [12] = act("h-mend", "mp", { match = "Mend Pet" }),
    [13] = act("h-mark", "hmark", { match = "Hunter's Mark" }),
    [14] = act("h-sting", "sting", { match = "Serpent Sting" }),
    [15] = act("h-clip", "wc", { match = "wc" }),
    [16] = act("spell:75", "Auto Shot", { match = "Auto Shot" }),
    [17] = act("h-cheetah", "cheetah", { match = "Aspect of the Cheetah" }),
    [18] = act("shared-pa", "pa", { match = "pa" }),
    [19] = act("spell:13161", "Aspect of the Beast", { match = "Aspect of the Beast" }),
    [20] = act("spell:13159", "Aspect of the Pack", { match = "Aspect of the Pack" }),
    [21] = act("h-wild", "wild", { match = "wild" }),
    [22] = act("spell:1462", "Beast Lore", { match = "Beast Lore" }),
    [23] = act("spell:2641", "Dismiss Pet", { match = "Dismiss Pet" }),
    [24] = act("spell:8690", "Hearthstone", { match = "Hearthstone" }),
    [25] = act("spell:6197", "Eagle Eye", { match = "Eagle Eye" }),
    [26] = act("spell:1002", "Eyes of the Beast", { match = "Eyes of the Beast" }),
    [27] = act("spell:6991", "Feed Pet", { match = "Feed Pet" }),
    [28] = act("spell:982", "Revive Pet", { match = "Revive Pet" }),
    [29] = act("h-scare", "scare", { match = "scare" }),
    [30] = act("spell:1515", "Tame Beast", { match = "Tame Beast" }),
    [31] = act("h-dshot", "dshot", { match = "dshot" }),
    [32] = act("spell:1543", "Flare", { match = "Flare" }),
    [33] = act("h-call", "pet", { match = "Call Pet" }),
    [34] = act("h-bw", "bw", { match = "Bestial Wrath" }),
    [35] = act("h-scorpid", "scorpid", { match = "scorpid" }),
    [36] = act("h-viper", "viper", { match = "viper" }),
    [37] = act("h-volley", "volley", { match = "volley" }),
    [38] = act("h-diseng", "diseng", { match = "diseng" }),
    [39] = act("h-etrap", "etrap", { match = "etrap" }),
    [40] = act("spell:13809", "Frost Trap", { match = "Frost Trap" }),
    [41] = act("h-itrap", "itrap", { match = "itrap" }),
    [42] = act("shared-pf", "pf", { match = "pf" }),
    [43] = act("h-mongo", "mongo", { match = "mongo" }),
    [44] = act("h-raptor", "raptor", { match = "raptor" }),
    [45] = act("spell:23989", "Readiness", { match = "Readiness" }),
    [46] = act("spell:1494", "Track Beasts", { match = "Track Beasts" }),
    [47] = act("spell:19878", "Track Demons", { match = "Track Demons" }),
    [48] = act("spell:19879", "Track Dragonkin", { match = "Track Dragonkin" }),
    [49] = act("spell:19880", "Track Elementals", { match = "Track Elementals" }),
    [50] = act("spell:19882", "Track Giants", { match = "Track Giants" }),
    [51] = act("spell:19885", "Track Hidden", { match = "Track Hidden" }),
    [52] = act("spell:19883", "Track Humanoids", { match = "Track Humanoids" }),
    [53] = act("spell:19884", "Track Undead", { match = "Track Undead" }),
    [73] = act("h-fd", "fd", { match = "Feign Death" }),
    [74] = act("h-clip", "wc", { match = "wc" }),
  },
}
