--[[
  Purpose: Shipped class defaults for MAGE (bar slot rotation).
  Deps: ShadowUI addon table
  Public: populates ShadowUI.Defaults.classes.MAGE
]]

local Addon = LibStub("AceAddon-3.0"):GetAddon("ShadowUI")
local act = Addon.Defaults.act

-- Spells stay in action slots 1-120. Mage rotates bars 2-6 so old bar6
-- (slots 61-72) sits on bar2; old 2→3, 3→4, 4→5, 5→6.
Addon.Defaults.classes.MAGE = {
  layout = {
    bar2 = { firstSlot = 61 },
    bar3 = { firstSlot = 13 },
    bar4 = { firstSlot = 25 },
    bar5 = { firstSlot = 37 },
    bar6 = { firstSlot = 49 },
  },
  keybinds = {
    ["CLICK ShadowUIActionButton1:Keybind"] = "Q",
    ["CLICK ShadowUIActionButton2:Keybind"] = "E",
    ["CLICK ShadowUIActionButton3:Keybind"] = "R",
    ["CLICK ShadowUIActionButton4:Keybind"] = "F",
    ["CLICK ShadowUIActionButton5:Keybind"] = "T",
    ["CLICK ShadowUIActionButton6:Keybind"] = "G",
    ["CLICK ShadowUIActionButton7:Keybind"] = "C",
    ["CLICK ShadowUIActionButton8:Keybind"] = "V",
    ["CLICK ShadowUIActionButton9:Keybind"] = "B",
    ["CLICK ShadowUIActionButton10:Keybind"] = "X",
    ["CLICK ShadowUIActionButton11:Keybind"] = "Z",
    ["CLICK ShadowUIActionButton12:Keybind"] = "H",
    ["CLICK ShadowUIActionButton13:Keybind"] = "SHIFT-G",
    ["CLICK ShadowUIActionButton14:Keybind"] = "SHIFT-C",
    ["CLICK ShadowUIActionButton15:Keybind"] = "SHIFT-V",
    ["CLICK ShadowUIActionButton16:Keybind"] = "SHIFT-B",
    ["CLICK ShadowUIActionButton17:Keybind"] = "SHIFT-X",
    ["CLICK ShadowUIActionButton18:Keybind"] = "SHIFT-Z",
    ["CLICK ShadowUIActionButton19:Keybind"] = "SHIFT-H",
    ["CLICK ShadowUIActionButton20:Keybind"] = "SHIFT-N",
    ["CLICK ShadowUIActionButton21:Keybind"] = "6",
    ["CLICK ShadowUIActionButton22:Keybind"] = "7",
    ["CLICK ShadowUIActionButton23:Keybind"] = "8",
    ["CLICK ShadowUIActionButton24:Keybind"] = "9",
    ["CLICK ShadowUIActionButton25:Keybind"] = "SHIFT-1",
    ["CLICK ShadowUIActionButton26:Keybind"] = "SHIFT-2",
    ["CLICK ShadowUIActionButton27:Keybind"] = "SHIFT-3",
    ["CLICK ShadowUIActionButton28:Keybind"] = "SHIFT-4",
    ["CLICK ShadowUIActionButton29:Keybind"] = "SHIFT-5",
    ["CLICK ShadowUIActionButton30:Keybind"] = "SHIFT-`",
    ["CLICK ShadowUIActionButton31:Keybind"] = "ALT-1",
    ["CLICK ShadowUIActionButton32:Keybind"] = "ALT-2",
    ["CLICK ShadowUIActionButton33:Keybind"] = "ALT-3",
    ["CLICK ShadowUIActionButton34:Keybind"] = "ALT-4",
    ["CLICK ShadowUIActionButton35:Keybind"] = "ALT-5",
    ["CLICK ShadowUIActionButton36:Keybind"] = "ALT-6",
    ["CLICK ShadowUIActionButton37:Keybind"] = "ALT-Q",
    ["CLICK ShadowUIActionButton38:Keybind"] = "ALT-E",
    ["CLICK ShadowUIActionButton39:Keybind"] = "ALT-R",
    ["CLICK ShadowUIActionButton40:Keybind"] = "ALT-F",
    ["CLICK ShadowUIActionButton41:Keybind"] = "ALT-T",
    ["CLICK ShadowUIActionButton42:Keybind"] = "ALT-G",
    ["CLICK ShadowUIActionButton43:Keybind"] = "ALT-C",
    ["CLICK ShadowUIActionButton44:Keybind"] = "ALT-V",
    ["CLICK ShadowUIActionButton45:Keybind"] = "ALT-B",
    ["CLICK ShadowUIActionButton46:Keybind"] = "ALT-X",
    ["CLICK ShadowUIActionButton47:Keybind"] = "ALT-Z",
    ["CLICK ShadowUIActionButton48:Keybind"] = "0",
    ["CLICK ShadowUIActionButton49:Keybind"] = "CTRL-Q",
    ["CLICK ShadowUIActionButton50:Keybind"] = "CTRL-E",
    ["CLICK ShadowUIActionButton51:Keybind"] = "CTRL-R",
    ["CLICK ShadowUIActionButton52:Keybind"] = "CTRL-F",
    ["CLICK ShadowUIActionButton53:Keybind"] = "CTRL-T",
    ["CLICK ShadowUIActionButton54:Keybind"] = "CTRL-G",
    ["CLICK ShadowUIActionButton55:Keybind"] = "CTRL-C",
    ["CLICK ShadowUIActionButton56:Keybind"] = "CTRL-V",
    ["CLICK ShadowUIActionButton57:Keybind"] = "CTRL-B",
    ["CLICK ShadowUIActionButton58:Keybind"] = "CTRL-1",
    ["CLICK ShadowUIActionButton59:Keybind"] = "CTRL-2",
    ["CLICK ShadowUIActionButton60:Keybind"] = "CTRL-3",
    ["CLICK ShadowUIActionButton61:Keybind"] = "1",
    ["CLICK ShadowUIActionButton62:Keybind"] = "2",
    ["CLICK ShadowUIActionButton63:Keybind"] = "3",
    ["CLICK ShadowUIActionButton64:Keybind"] = "4",
    ["CLICK ShadowUIActionButton65:Keybind"] = "5",
    ["CLICK ShadowUIActionButton66:Keybind"] = "`",
    ["CLICK ShadowUIActionButton67:Keybind"] = "SHIFT-Q",
    ["CLICK ShadowUIActionButton68:Keybind"] = "SHIFT-E",
    ["CLICK ShadowUIActionButton69:Keybind"] = "SHIFT-R",
    ["CLICK ShadowUIActionButton70:Keybind"] = "SHIFT-F",
    ["CLICK ShadowUIActionButton71:Keybind"] = "SHIFT-T",
    ["CLICK ShadowUIActionButton72:Keybind"] = "N",
    ["CLICK ShadowUIActionButton73:Keybind"] = "BUTTON5",
    ["CLICK ShadowUIActionButton74:Keybind"] = "BUTTON4",
    ["CLICK ShadowUIActionButton75:Keybind"] = "BUTTON3",
    ["CLICK ShadowUIActionButton76:Keybind"] = "ALT-SHIFT-1",
    ["CLICK ShadowUIActionButton77:Keybind"] = "ALT-SHIFT-2",
    ["CLICK ShadowUIActionButton78:Keybind"] = "ALT-SHIFT-3",
    ["CLICK ShadowUIActionButton79:Keybind"] = "F1",
    ["CLICK ShadowUIActionButton80:Keybind"] = "ALT-SHIFT-Q",
    ["CLICK ShadowUIActionButton81:Keybind"] = "ALT-SHIFT-E",
    ["CLICK ShadowUIActionButton82:Keybind"] = "ALT-SHIFT-R",
    ["CLICK ShadowUIActionButton83:Keybind"] = "ALT-SHIFT-F",
    ["CLICK ShadowUIActionButton84:Keybind"] = "ALT-SHIFT-C",
  },
  actions = {
    [1] = act("m-ae", "ae", { match = "ae" }),
    [2] = act("m-blast", "'", { match = "'" }),
    [3] = act("m-blizz", "Blizz", { match = "Blizz" }),
    [4] = act("spell:1953", "Blink", {
      kind = "spell",
      spellId = 1953,
    }),
    [5] = act("m-fs", "fs", { match = "fs" }),
    [6] = act("m-cs", "CS", { match = CS }),
    [7] = act("m-cone", "cone", { match = "cone" }),
    [8] = act("m-nova", "fn", { match = "Frost Nova" }),
    [9] = act("m-ib", "ib", { match = "Ice block" }),
    [12] = act("spell:12051", "Evocation", {
      kind = "spell",
      spellId = 12051,
    }),
    [13] = act("m-decurse", "decurse", { match = "Remove Lesser Curse" }),
    [14] = act("m-am", "am", { match = "Arcane Missiles" }),
    [15] = act("spell:28612", "Conjure Food", {
      kind = "spell",
      spellId = 28612,
    }),
    [16] = act("spell:759", "Conjure Mana Agate", {
      kind = "spell",
      spellId = 759,
    }),
    [17] = act("m-ma", "ma", { match = "ma" }),
    [18] = act("spell:10053", "Conjure Mana Citrine", {
      kind = "spell",
      spellId = 10053,
    }),
    [19] = act("spell:3552", "Conjure Mana Jade", {
      kind = "spell",
      spellId = 3552,
    }),
    [20] = act("spell:10054", "Conjure Mana Ruby", {
      kind = "spell",
      spellId = 10054,
    }),
    [22] = act("m-pyro", "py", { match = "Pyroblast" }),
    [23] = act("spell:10140", "Conjure Water", {
      kind = "spell",
      spellId = 10140,
    }),
    [24] = act("spell:2855", "Detect Magic", {
      kind = "spell",
      spellId = 2855,
    }),
    [25] = act("m-slowfall", "slowfall", { match = "Slow Fall" }),
    [26] = act("m-ai", "ai", { match = "ai" }),
    [27] = act("m-ia", "ia", { match = "ia" }),
    [28] = act("m-dampen", "dm", { match = "dm" }),
    [30] = act("m-sw", "portsw", { match = "portsw" }),
    [31] = act("m-if", "if", { match = "if" }),
    [32] = act("m-dar", "dar", { match = "dar" }),
    [35] = act("m-cf", "cf", { match = "cf" }),
    [61] = act("m-fb", "f", { match = "f" }),
    [62] = act("m-fireball", "fb", { match = "Fireball" }),
    [63] = act("m-scorch", "sc", { match = "Scorch" }),
    [64] = act("m-blast", "'", { match = "'" }),
    [65] = act("m-sheep", "sheep", { match = "sheep" }),
    [66] = act("spell:5019", "Shoot", {
      kind = "spell",
      spellId = 5019,
    }),
    [69] = act("shared-t13", "t13", { match = "t13" }),
    [70] = act("shared-t14", "t14", { match = "t14" }),
    [72] = act("m-csnap", "snap", { match = "Cold Snap" }),
    [73] = act("m-barrier", "iba", { match = "Ice Barrier" }),
    [74] = act("m-ward", "ward", { match = "[mod:shift] Fire Ward; Frost Ward" }),
    [75] = act("m-ms", "MS", { match = MS }),
  },
}
