--[[
  Purpose: Shipped class defaults for PALADIN.
  Deps: ShadowUI addon table
  Public: populates ShadowUI.Defaults.classes.PALADIN
]]

local Addon = LibStub("AceAddon-3.0"):GetAddon("ShadowUI")
local act = Addon.Defaults.act

Addon.Defaults.classes.PALADIN = {
  layout = {},
  keybinds = {
    ["CLICK ShadowUIActionButton1:Keybind"] = "Q",
    ["CLICK ShadowUIActionButton2:Keybind"] = "E",
    ["CLICK ShadowUIActionButton3:Keybind"] = "R",
    ["CLICK ShadowUIActionButton4:Keybind"] = "F",
    ["CLICK ShadowUIActionButton5:Keybind"] = "T",
    ["CLICK ShadowUIActionButton6:Keybind"] = "G",
    ["CLICK ShadowUIActionButton7:Keybind"] = "C",
    ["CLICK ShadowUIActionButton8:Keybind"] = "V",
    ["CLICK ShadowUIActionButton9:Keybind"] = "B",
    ["CLICK ShadowUIActionButton10:Keybind"] = "X",
    ["CLICK ShadowUIActionButton11:Keybind"] = "Z",
    ["CLICK ShadowUIActionButton12:Keybind"] = "H",
    ["CLICK ShadowUIActionButton13:Keybind"] = "1",
    ["CLICK ShadowUIActionButton14:Keybind"] = "2",
    ["CLICK ShadowUIActionButton15:Keybind"] = "3",
    ["CLICK ShadowUIActionButton16:Keybind"] = "4",
    ["CLICK ShadowUIActionButton17:Keybind"] = "5",
    ["CLICK ShadowUIActionButton18:Keybind"] = "`",
    ["CLICK ShadowUIActionButton19:Keybind"] = "SHIFT-Q",
    ["CLICK ShadowUIActionButton20:Keybind"] = "SHIFT-E",
    ["CLICK ShadowUIActionButton21:Keybind"] = "SHIFT-R",
    ["CLICK ShadowUIActionButton22:Keybind"] = "SHIFT-F",
    ["CLICK ShadowUIActionButton23:Keybind"] = "SHIFT-T",
    ["CLICK ShadowUIActionButton24:Keybind"] = "N",
    ["CLICK ShadowUIActionButton25:Keybind"] = "SHIFT-G",
    ["CLICK ShadowUIActionButton26:Keybind"] = "SHIFT-C",
    ["CLICK ShadowUIActionButton27:Keybind"] = "SHIFT-V",
    ["CLICK ShadowUIActionButton28:Keybind"] = "SHIFT-B",
    ["CLICK ShadowUIActionButton29:Keybind"] = "SHIFT-X",
    ["CLICK ShadowUIActionButton30:Keybind"] = "SHIFT-Z",
    ["CLICK ShadowUIActionButton31:Keybind"] = "SHIFT-H",
    ["CLICK ShadowUIActionButton32:Keybind"] = "SHIFT-N",
    ["CLICK ShadowUIActionButton33:Keybind"] = "6",
    ["CLICK ShadowUIActionButton34:Keybind"] = "7",
    ["CLICK ShadowUIActionButton35:Keybind"] = "8",
    ["CLICK ShadowUIActionButton36:Keybind"] = "9",
    ["CLICK ShadowUIActionButton37:Keybind"] = "SHIFT-1",
    ["CLICK ShadowUIActionButton38:Keybind"] = "SHIFT-2",
    ["CLICK ShadowUIActionButton39:Keybind"] = "SHIFT-3",
    ["CLICK ShadowUIActionButton40:Keybind"] = "SHIFT-4",
    ["CLICK ShadowUIActionButton41:Keybind"] = "SHIFT-5",
    ["CLICK ShadowUIActionButton42:Keybind"] = "SHIFT-`",
    ["CLICK ShadowUIActionButton43:Keybind"] = "ALT-1",
    ["CLICK ShadowUIActionButton44:Keybind"] = "ALT-2",
    ["CLICK ShadowUIActionButton45:Keybind"] = "ALT-3",
    ["CLICK ShadowUIActionButton46:Keybind"] = "ALT-4",
    ["CLICK ShadowUIActionButton47:Keybind"] = "ALT-5",
    ["CLICK ShadowUIActionButton48:Keybind"] = "ALT-6",
    ["CLICK ShadowUIActionButton49:Keybind"] = "ALT-Q",
    ["CLICK ShadowUIActionButton50:Keybind"] = "ALT-E",
    ["CLICK ShadowUIActionButton51:Keybind"] = "ALT-R",
    ["CLICK ShadowUIActionButton52:Keybind"] = "ALT-F",
    ["CLICK ShadowUIActionButton53:Keybind"] = "ALT-T",
    ["CLICK ShadowUIActionButton54:Keybind"] = "ALT-G",
    ["CLICK ShadowUIActionButton55:Keybind"] = "ALT-C",
    ["CLICK ShadowUIActionButton56:Keybind"] = "ALT-V",
    ["CLICK ShadowUIActionButton57:Keybind"] = "ALT-B",
    ["CLICK ShadowUIActionButton58:Keybind"] = "ALT-X",
    ["CLICK ShadowUIActionButton59:Keybind"] = "ALT-Z",
    ["CLICK ShadowUIActionButton60:Keybind"] = "0",
    ["CLICK ShadowUIActionButton61:Keybind"] = "CTRL-Q",
    ["CLICK ShadowUIActionButton62:Keybind"] = "CTRL-E",
    ["CLICK ShadowUIActionButton63:Keybind"] = "CTRL-R",
    ["CLICK ShadowUIActionButton64:Keybind"] = "CTRL-F",
    ["CLICK ShadowUIActionButton65:Keybind"] = "CTRL-T",
    ["CLICK ShadowUIActionButton66:Keybind"] = "CTRL-G",
    ["CLICK ShadowUIActionButton67:Keybind"] = "CTRL-C",
    ["CLICK ShadowUIActionButton68:Keybind"] = "CTRL-V",
    ["CLICK ShadowUIActionButton69:Keybind"] = "CTRL-B",
    ["CLICK ShadowUIActionButton70:Keybind"] = "CTRL-1",
    ["CLICK ShadowUIActionButton71:Keybind"] = "CTRL-2",
    ["CLICK ShadowUIActionButton72:Keybind"] = "CTRL-3",
    ["CLICK ShadowUIActionButton73:Keybind"] = "BUTTON5",
    ["CLICK ShadowUIActionButton74:Keybind"] = "BUTTON4",
    ["CLICK ShadowUIActionButton75:Keybind"] = "BUTTON3",
    ["CLICK ShadowUIActionButton76:Keybind"] = "ALT-SHIFT-1",
    ["CLICK ShadowUIActionButton77:Keybind"] = "ALT-SHIFT-2",
    ["CLICK ShadowUIActionButton78:Keybind"] = "ALT-SHIFT-3",
    ["CLICK ShadowUIActionButton79:Keybind"] = "F1",
    ["CLICK ShadowUIActionButton80:Keybind"] = "ALT-SHIFT-Q",
    ["CLICK ShadowUIActionButton81:Keybind"] = "ALT-SHIFT-E",
    ["CLICK ShadowUIActionButton82:Keybind"] = "ALT-SHIFT-R",
    ["CLICK ShadowUIActionButton83:Keybind"] = "ALT-SHIFT-F",
    ["CLICK ShadowUIActionButton84:Keybind"] = "ALT-SHIFT-C",
  },
  actions = {
    [1] = act("p-judge", "judge", { match = "Judgement" }),
    [2] = act("p-seal", "seal", { match = "seal" }),
    [3] = act("p-cons", "cons", { match = "cons" }),
    [4] = act("p-bop", "bop", { match = "Blessing of Protection" }),
    [5] = act("shared-t13", "t13", { match = "t13" }),
    [7] = act("p-hoj", "hoj", { match = "Hammer of Justice" }),
    [8] = act("p-cleanse", "cl", { match = "Cleanse" }),
    [9] = act("p-rf", "rf", { match = "Righteous Fury" }),
    [10] = act("p-rep", "rep", { match = "Repentance" }),
    [11] = act("p-bubble", "bubble", { match = "Divine Shield" }),
    [12] = act("p-fol", "fol", { match = "fol" }),
    [13] = act("p-how", "how", { match = "Hammer of Wrath" }),
    [14] = act("p-exo", "exo", { match = "Exorcism" }),
    [15] = act("p-might", "bom", { match = "bom" }),
    [16] = act("p-aura", "aura", { match = "aura" }),
    [17] = act("p-hl", "hl", { match = "hl" }),
    [18] = act("p-gbom", "gbom", { match = "gbom" }),
    [19] = act("p-crus", "crus", { match = "crus" }),
    [20] = act("spell:1044", "Blessing of Freedom", {
      kind = "spell",
      spellId = 1044,
    }),
    [21] = act("p-bosac", "bosac", { match = "bosac" }),
    [22] = act("p-dprot", "dprot", { match = "dprot" }),
    [23] = act("p-fraura", "fraura", { match = "fraura" }),
    [24] = act("spell:8690", "Hearthstone", {
      kind = "spell",
      spellId = 8690,
    }),
    [25] = act("p-rfaura", "rfaura", { match = "rfaura" }),
    [26] = act("spell:25895", "Greater Blessing of Salvation", {
      kind = "spell",
      spellId = 25895,
    }),
    [27] = act("spell:20164", "Seal of Justice", {
      kind = "spell",
      spellId = 20164,
    }),
    [28] = act("p-sraura", "sraura", { match = "sraura" }),
    [29] = act("p-bolight", "bolight", { match = "bolight" }),
    [30] = act("p-cancel-ds", "cds", { match = "cds" }),
    [31] = act("spell:25890", "Greater Blessing of Light", {
      kind = "spell",
      spellId = 25890,
    }),
    [32] = act("p-gbow", "gbow", { match = "gbow" }),
    [33] = act("p-loh", "loh", { match = "Lay on Hands" }),
    [34] = act("p-di", "di", { match = "Divine Intervention" }),
    [35] = act("p-hwath", "hwath", { match = "hwath" }),
    [36] = act("spell:1152", "Purify", {
      kind = "spell",
      spellId = 1152,
    }),
    [37] = act("p-redeem", "redeem", { match = "redeem" }),
    [38] = act("p-seal-h", "sealh", { match = "sealh" }),
    [40] = act("spell:5502", "Sense Undead", {
      kind = "spell",
      spellId = 5502,
    }),
    [41] = act("p-turnu", "turnu", { match = "turnu" }),
    [74] = act("p-judge", "judge", { match = "Judgement" }),
    [79] = act("p-mount", "chg", { match = "chg" }),
  },
}
