--[[
  Purpose: Shipped class defaults for PRIEST.
  Deps: ShadowUI addon table
  Public: populates ShadowUI.Defaults.classes.PRIEST
]]

local Addon = LibStub("AceAddon-3.0"):GetAddon("ShadowUI")
local act = Addon.Defaults.act

Addon.Defaults.classes.PRIEST = {
  layout = {},
  keybinds = {
    ["CLICK ShadowUIActionButton1:Keybind"] = "Q",
    ["CLICK ShadowUIActionButton2:Keybind"] = "E",
    ["CLICK ShadowUIActionButton3:Keybind"] = "R",
    ["CLICK ShadowUIActionButton4:Keybind"] = "F",
    ["CLICK ShadowUIActionButton5:Keybind"] = "T",
    ["CLICK ShadowUIActionButton6:Keybind"] = "G",
    ["CLICK ShadowUIActionButton7:Keybind"] = "C",
    ["CLICK ShadowUIActionButton8:Keybind"] = "V",
    ["CLICK ShadowUIActionButton9:Keybind"] = "B",
    ["CLICK ShadowUIActionButton10:Keybind"] = "X",
    ["CLICK ShadowUIActionButton11:Keybind"] = "Z",
    ["CLICK ShadowUIActionButton12:Keybind"] = "H",
    ["CLICK ShadowUIActionButton13:Keybind"] = "1",
    ["CLICK ShadowUIActionButton14:Keybind"] = "2",
    ["CLICK ShadowUIActionButton15:Keybind"] = "3",
    ["CLICK ShadowUIActionButton16:Keybind"] = "4",
    ["CLICK ShadowUIActionButton17:Keybind"] = "5",
    ["CLICK ShadowUIActionButton18:Keybind"] = "`",
    ["CLICK ShadowUIActionButton19:Keybind"] = "SHIFT-Q",
    ["CLICK ShadowUIActionButton20:Keybind"] = "SHIFT-E",
    ["CLICK ShadowUIActionButton21:Keybind"] = "SHIFT-R",
    ["CLICK ShadowUIActionButton22:Keybind"] = "SHIFT-F",
    ["CLICK ShadowUIActionButton23:Keybind"] = "SHIFT-T",
    ["CLICK ShadowUIActionButton24:Keybind"] = "N",
    ["CLICK ShadowUIActionButton25:Keybind"] = "SHIFT-G",
    ["CLICK ShadowUIActionButton26:Keybind"] = "SHIFT-C",
    ["CLICK ShadowUIActionButton27:Keybind"] = "SHIFT-V",
    ["CLICK ShadowUIActionButton28:Keybind"] = "SHIFT-B",
    ["CLICK ShadowUIActionButton29:Keybind"] = "SHIFT-X",
    ["CLICK ShadowUIActionButton30:Keybind"] = "SHIFT-Z",
    ["CLICK ShadowUIActionButton31:Keybind"] = "SHIFT-H",
    ["CLICK ShadowUIActionButton32:Keybind"] = "SHIFT-N",
    ["CLICK ShadowUIActionButton33:Keybind"] = "6",
    ["CLICK ShadowUIActionButton34:Keybind"] = "7",
    ["CLICK ShadowUIActionButton35:Keybind"] = "8",
    ["CLICK ShadowUIActionButton36:Keybind"] = "9",
    ["CLICK ShadowUIActionButton37:Keybind"] = "SHIFT-1",
    ["CLICK ShadowUIActionButton38:Keybind"] = "SHIFT-2",
    ["CLICK ShadowUIActionButton39:Keybind"] = "SHIFT-3",
    ["CLICK ShadowUIActionButton40:Keybind"] = "SHIFT-4",
    ["CLICK ShadowUIActionButton41:Keybind"] = "SHIFT-5",
    ["CLICK ShadowUIActionButton42:Keybind"] = "SHIFT-`",
    ["CLICK ShadowUIActionButton43:Keybind"] = "ALT-1",
    ["CLICK ShadowUIActionButton44:Keybind"] = "ALT-2",
    ["CLICK ShadowUIActionButton45:Keybind"] = "ALT-3",
    ["CLICK ShadowUIActionButton46:Keybind"] = "ALT-4",
    ["CLICK ShadowUIActionButton47:Keybind"] = "ALT-5",
    ["CLICK ShadowUIActionButton48:Keybind"] = "ALT-6",
    ["CLICK ShadowUIActionButton49:Keybind"] = "ALT-Q",
    ["CLICK ShadowUIActionButton50:Keybind"] = "ALT-E",
    ["CLICK ShadowUIActionButton51:Keybind"] = "ALT-R",
    ["CLICK ShadowUIActionButton52:Keybind"] = "ALT-F",
    ["CLICK ShadowUIActionButton53:Keybind"] = "ALT-T",
    ["CLICK ShadowUIActionButton54:Keybind"] = "ALT-G",
    ["CLICK ShadowUIActionButton55:Keybind"] = "ALT-C",
    ["CLICK ShadowUIActionButton56:Keybind"] = "ALT-V",
    ["CLICK ShadowUIActionButton57:Keybind"] = "ALT-B",
    ["CLICK ShadowUIActionButton58:Keybind"] = "ALT-X",
    ["CLICK ShadowUIActionButton59:Keybind"] = "ALT-Z",
    ["CLICK ShadowUIActionButton60:Keybind"] = "0",
    ["CLICK ShadowUIActionButton61:Keybind"] = "CTRL-Q",
    ["CLICK ShadowUIActionButton62:Keybind"] = "CTRL-E",
    ["CLICK ShadowUIActionButton63:Keybind"] = "CTRL-R",
    ["CLICK ShadowUIActionButton64:Keybind"] = "CTRL-F",
    ["CLICK ShadowUIActionButton65:Keybind"] = "CTRL-T",
    ["CLICK ShadowUIActionButton66:Keybind"] = "CTRL-G",
    ["CLICK ShadowUIActionButton67:Keybind"] = "CTRL-C",
    ["CLICK ShadowUIActionButton68:Keybind"] = "CTRL-V",
    ["CLICK ShadowUIActionButton69:Keybind"] = "CTRL-B",
    ["CLICK ShadowUIActionButton70:Keybind"] = "CTRL-1",
    ["CLICK ShadowUIActionButton71:Keybind"] = "CTRL-2",
    ["CLICK ShadowUIActionButton72:Keybind"] = "CTRL-3",
    ["CLICK ShadowUIActionButton73:Keybind"] = "BUTTON5",
    ["CLICK ShadowUIActionButton74:Keybind"] = "BUTTON4",
    ["CLICK ShadowUIActionButton75:Keybind"] = "BUTTON3",
    ["CLICK ShadowUIActionButton76:Keybind"] = "ALT-SHIFT-1",
    ["CLICK ShadowUIActionButton77:Keybind"] = "ALT-SHIFT-2",
    ["CLICK ShadowUIActionButton78:Keybind"] = "ALT-SHIFT-3",
    ["CLICK ShadowUIActionButton79:Keybind"] = "F1",
    ["CLICK ShadowUIActionButton80:Keybind"] = "ALT-SHIFT-Q",
    ["CLICK ShadowUIActionButton81:Keybind"] = "ALT-SHIFT-E",
    ["CLICK ShadowUIActionButton82:Keybind"] = "ALT-SHIFT-R",
    ["CLICK ShadowUIActionButton83:Keybind"] = "ALT-SHIFT-F",
    ["CLICK ShadowUIActionButton84:Keybind"] = "ALT-SHIFT-C",
  },
  actions = {
    [1] = act("pr-fh", "fh", { match = "fh" }),
    [2] = act("pr-renew", "rn", { match = "rn" }),
    [3] = act("pr-gh", "gh", { match = "gh" }),
    [4] = act("pr-pws", "pws", { match = "pws" }),
    [5] = act("shared-t13", "t13", { match = "t13" }),
    [7] = act("pr-scream", "ps", { match = "Psychic Scream" }),
    [8] = act("pr-dispel", "disp", { match = "Dispel Magic" }),
    [9] = act("pr-fort", "fort", { match = "Power Word: Fortitude" }),
    [10] = act("pr-shackle", "shk", { match = "Shackle Undead" }),
    [11] = act("pr-fade", "fade", { match = "Fade" }),
    [12] = act("pr-abolish", "ad", { match = "Abolish Disease" }),
    [13] = act("pr-mf", "mf", { match = "Mind Flay" }),
    [14] = act("pr-swp", "swp", { match = "swp" }),
    [15] = act("pr-mb", "mblast", { match = "Mind Blast" }),
    [16] = act("pr-wand", "wand", { match = "Shoot" }),
    [17] = act("pr-if", "ifr", { match = "Inner Fire" }),
    [18] = act("pr-egrace", "egrace", { match = "egrace" }),
    [19] = act("pr-fback", "fback", { match = "fback" }),
    [20] = act("spell:1706", "Levitate", {
      kind = "spell",
      spellId = 1706,
    }),
    [21] = act("pr-mburn", "mburn", { match = "mburn" }),
    [22] = act("pr-shards", "shards", { match = "shards" }),
    [23] = act("pr-pi", "pi", { match = "Power Infusion" }),
    [24] = act("pr-pof", "pof", { match = "Prayer of Fortitude" }),
    [25] = act("spell:528", "Cure Disease", {
      kind = "spell",
      spellId = 528,
    }),
    [26] = act("pr-dpray", "dpray", { match = "dpray" }),
    [27] = act("pr-heal", "heal", { match = "heal" }),
    [28] = act("pr-hfire", "hfire", { match = "hfire" }),
    [29] = act("pr-lheal", "lheal", { match = "lheal" }),
    [30] = act("pr-sf", "sf", { match = "Shadowform" }),
    [31] = act("pr-poh", "poh", { match = "Prayer of Healing" }),
    [32] = act("pr-smite", "smite", { match = "smite" }),
    [33] = act("pr-nova", "hn", { match = "hn" }),
    [34] = act("pr-rez", "rez", { match = "Resurrection" }),
    [35] = act("pr-fw", "fw", { match = "Fear Ward" }),
    [36] = act("pr-spirit", "pos", { match = "Prayer of Spirit" }),
    [37] = act("pr-dplague", "dplague", { match = "dplague" }),
    [38] = act("pr-hexw", "hexw", { match = "hexw" }),
    [39] = act("pr-mc", "mc", { match = "mc" }),
    [40] = act("pr-msoothe", "msoothe", { match = "msoothe" }),
    [41] = act("pr-mvis", "mvis", { match = "mvis" }),
    [42] = act("spell:27683", "Prayer of Shadow Protection", {
      kind = "spell",
      spellId = 27683,
    }),
    [43] = act("pr-sprot", "sprot", { match = "sprot" }),
    [44] = act("pr-sguard", "sguard", { match = "sguard" }),
    [45] = act("pr-tow", "tow", { match = "tow" }),
    [74] = act("pr-swp", "swp", { match = "swp" }),
  },
}
