--[[
  Purpose: Shipped class defaults for SHAMAN.
  Deps: ShadowUI addon table
  Public: populates ShadowUI.Defaults.classes.SHAMAN
]]

local Addon = LibStub("AceAddon-3.0"):GetAddon("ShadowUI")
local act = Addon.Defaults.act

Addon.Defaults.classes.SHAMAN = {
  layout = {},
  keybinds = {
    ["CLICK ShadowUIActionButton1:Keybind"] = "Q",
    ["CLICK ShadowUIActionButton2:Keybind"] = "E",
    ["CLICK ShadowUIActionButton3:Keybind"] = "R",
    ["CLICK ShadowUIActionButton4:Keybind"] = "F",
    ["CLICK ShadowUIActionButton5:Keybind"] = "T",
    ["CLICK ShadowUIActionButton6:Keybind"] = "G",
    ["CLICK ShadowUIActionButton7:Keybind"] = "C",
    ["CLICK ShadowUIActionButton8:Keybind"] = "V",
    ["CLICK ShadowUIActionButton9:Keybind"] = "B",
    ["CLICK ShadowUIActionButton10:Keybind"] = "X",
    ["CLICK ShadowUIActionButton11:Keybind"] = "Z",
    ["CLICK ShadowUIActionButton12:Keybind"] = "H",
    ["CLICK ShadowUIActionButton13:Keybind"] = "1",
    ["CLICK ShadowUIActionButton14:Keybind"] = "2",
    ["CLICK ShadowUIActionButton15:Keybind"] = "3",
    ["CLICK ShadowUIActionButton16:Keybind"] = "4",
    ["CLICK ShadowUIActionButton17:Keybind"] = "5",
    ["CLICK ShadowUIActionButton18:Keybind"] = "`",
    ["CLICK ShadowUIActionButton19:Keybind"] = "SHIFT-Q",
    ["CLICK ShadowUIActionButton20:Keybind"] = "SHIFT-E",
    ["CLICK ShadowUIActionButton21:Keybind"] = "SHIFT-R",
    ["CLICK ShadowUIActionButton22:Keybind"] = "SHIFT-F",
    ["CLICK ShadowUIActionButton23:Keybind"] = "SHIFT-T",
    ["CLICK ShadowUIActionButton24:Keybind"] = "N",
    ["CLICK ShadowUIActionButton25:Keybind"] = "SHIFT-G",
    ["CLICK ShadowUIActionButton26:Keybind"] = "SHIFT-C",
    ["CLICK ShadowUIActionButton27:Keybind"] = "SHIFT-V",
    ["CLICK ShadowUIActionButton28:Keybind"] = "SHIFT-B",
    ["CLICK ShadowUIActionButton29:Keybind"] = "SHIFT-X",
    ["CLICK ShadowUIActionButton30:Keybind"] = "SHIFT-Z",
    ["CLICK ShadowUIActionButton31:Keybind"] = "SHIFT-H",
    ["CLICK ShadowUIActionButton32:Keybind"] = "SHIFT-N",
    ["CLICK ShadowUIActionButton33:Keybind"] = "6",
    ["CLICK ShadowUIActionButton34:Keybind"] = "7",
    ["CLICK ShadowUIActionButton35:Keybind"] = "8",
    ["CLICK ShadowUIActionButton36:Keybind"] = "9",
    ["CLICK ShadowUIActionButton37:Keybind"] = "SHIFT-1",
    ["CLICK ShadowUIActionButton38:Keybind"] = "SHIFT-2",
    ["CLICK ShadowUIActionButton39:Keybind"] = "SHIFT-3",
    ["CLICK ShadowUIActionButton40:Keybind"] = "SHIFT-4",
    ["CLICK ShadowUIActionButton41:Keybind"] = "SHIFT-5",
    ["CLICK ShadowUIActionButton42:Keybind"] = "SHIFT-`",
    ["CLICK ShadowUIActionButton43:Keybind"] = "ALT-1",
    ["CLICK ShadowUIActionButton44:Keybind"] = "ALT-2",
    ["CLICK ShadowUIActionButton45:Keybind"] = "ALT-3",
    ["CLICK ShadowUIActionButton46:Keybind"] = "ALT-4",
    ["CLICK ShadowUIActionButton47:Keybind"] = "ALT-5",
    ["CLICK ShadowUIActionButton48:Keybind"] = "ALT-6",
    ["CLICK ShadowUIActionButton49:Keybind"] = "ALT-Q",
    ["CLICK ShadowUIActionButton50:Keybind"] = "ALT-E",
    ["CLICK ShadowUIActionButton51:Keybind"] = "ALT-R",
    ["CLICK ShadowUIActionButton52:Keybind"] = "ALT-F",
    ["CLICK ShadowUIActionButton53:Keybind"] = "ALT-T",
    ["CLICK ShadowUIActionButton54:Keybind"] = "ALT-G",
    ["CLICK ShadowUIActionButton55:Keybind"] = "ALT-C",
    ["CLICK ShadowUIActionButton56:Keybind"] = "ALT-V",
    ["CLICK ShadowUIActionButton57:Keybind"] = "ALT-B",
    ["CLICK ShadowUIActionButton58:Keybind"] = "ALT-X",
    ["CLICK ShadowUIActionButton59:Keybind"] = "ALT-Z",
    ["CLICK ShadowUIActionButton60:Keybind"] = "0",
    ["CLICK ShadowUIActionButton61:Keybind"] = "CTRL-Q",
    ["CLICK ShadowUIActionButton62:Keybind"] = "CTRL-E",
    ["CLICK ShadowUIActionButton63:Keybind"] = "CTRL-R",
    ["CLICK ShadowUIActionButton64:Keybind"] = "CTRL-F",
    ["CLICK ShadowUIActionButton65:Keybind"] = "CTRL-T",
    ["CLICK ShadowUIActionButton66:Keybind"] = "CTRL-G",
    ["CLICK ShadowUIActionButton67:Keybind"] = "CTRL-C",
    ["CLICK ShadowUIActionButton68:Keybind"] = "CTRL-V",
    ["CLICK ShadowUIActionButton69:Keybind"] = "CTRL-B",
    ["CLICK ShadowUIActionButton70:Keybind"] = "CTRL-1",
    ["CLICK ShadowUIActionButton71:Keybind"] = "CTRL-2",
    ["CLICK ShadowUIActionButton72:Keybind"] = "CTRL-3",
    ["CLICK ShadowUIActionButton73:Keybind"] = "BUTTON5",
    ["CLICK ShadowUIActionButton74:Keybind"] = "BUTTON4",
    ["CLICK ShadowUIActionButton75:Keybind"] = "BUTTON3",
    ["CLICK ShadowUIActionButton76:Keybind"] = "ALT-SHIFT-1",
    ["CLICK ShadowUIActionButton77:Keybind"] = "ALT-SHIFT-2",
    ["CLICK ShadowUIActionButton78:Keybind"] = "ALT-SHIFT-3",
    ["CLICK ShadowUIActionButton79:Keybind"] = "F1",
    ["CLICK ShadowUIActionButton80:Keybind"] = "ALT-SHIFT-Q",
    ["CLICK ShadowUIActionButton81:Keybind"] = "ALT-SHIFT-E",
    ["CLICK ShadowUIActionButton82:Keybind"] = "ALT-SHIFT-R",
    ["CLICK ShadowUIActionButton83:Keybind"] = "ALT-SHIFT-F",
    ["CLICK ShadowUIActionButton84:Keybind"] = "ALT-SHIFT-C",
  },
  actions = {
    [1] = act("s-ss", "storm", { match = "Stormstrike" }),
    [2] = act("s-shock", "fl", { match = "fl" }),
    [3] = act("s-lb", "lb", { match = "lb" }),
    [4] = act("s-es", "es", { match = "Earth Shock" }),
    [5] = act("shared-t13", "t13", { match = "t13" }),
    [7] = act("s-ground", "gt", { match = "gt" }),
    [8] = act("s-purge", "pg", { match = "Purge" }),
    [9] = act("s-tide", "mt", { match = "Mana Tide Totem" }),
    [10] = act("s-cure", "cure", { match = "Cure Poison" }),
    [11] = act("s-ns", "ns", { match = "Healing Wave" }),
    [12] = act("s-lhw", "lhw", { match = "lhw" }),
    [13] = act("s-ls", "lshield", { match = "Lightning Shield" }),
    [14] = act("s-cl", "chain", { match = "Chain Lightning" }),
    [15] = act("s-cheal", "cheal", { match = "cheal" }),
    [16] = act("s-str", "str", { match = "Strength of Earth Totem" }),
    [17] = act("s-tremor", "tt", { match = "Tremor Totem" }),
    [18] = act("spell:2484", "Earthbind Totem", { match = "Earthbind Totem" }),
    [19] = act("s-fnt", "fnt", { match = "fnt" }),
    [20] = act("s-magma", "magma", { match = "magma" }),
    [21] = act("s-mana", "mst", { match = "Mana Spring Totem" }),
    [22] = act("s-sear", "sear", { match = "sear" }),
    [23] = act("s-sclaw", "sclaw", { match = "sclaw" }),
    [24] = act("s-wolf", "gw", { match = "Ghost Wolf" }),
    [25] = act("spell:556", "Astral Recall", { match = "Astral Recall" }),
    [26] = act("spell:6196", "Far Sight", { match = "Far Sight" }),
    [27] = act("s-frtot", "frtot", { match = "frtot" }),
    [28] = act("s-fttot", "fttot", { match = "fttot" }),
    [29] = act("s-rftot", "rftot", { match = "rftot" }),
    [30] = act("s-fbrand", "fbrand", { match = "fbrand" }),
    [31] = act("s-goa", "goa", { match = "goa" }),
    [32] = act("s-nrtot", "nrtot", { match = "nrtot" }),
    [33] = act("s-hw", "hw", { match = "hw" }),
    [34] = act("s-wf", "wf", { match = "wf" }),
    [35] = act("s-rbit", "rbit", { match = "rbit" }),
    [36] = act("spell:6495", "Sentry Totem", { match = "Sentry Totem" }),
    [37] = act("s-sskin", "sskin", { match = "sskin" }),
    [38] = act("spell:131", "Water Breathing", { match = "Water Breathing" }),
    [39] = act("spell:546", "Water Walking", { match = "Water Walking" }),
    [40] = act("s-wwall", "wwall", { match = "wwall" }),
    [41] = act("s-aspirit", "aspirit", { match = "aspirit" }),
    [42] = act("spell:2870", "Cure Disease", { match = "Cure Disease" }),
    [43] = act("spell:8170", "Disease Cleansing Totem", { match = "Disease Cleansing Totem" }),
    [44] = act("s-hstot", "hstot", { match = "hstot" }),
    [45] = act("spell:8166", "Poison Cleansing Totem", { match = "Poison Cleansing Totem" }),
    [46] = act("spell:25908", "Tranquil Air Totem", { match = "Tranquil Air Totem" }),
  },
}
