--[[
  Purpose: Shipped class defaults for WARLOCK (pet bar uses base placement).
  Deps: ShadowUI addon table
  Public: populates ShadowUI.Defaults.classes.WARLOCK
]]

local Addon = LibStub("AceAddon-3.0"):GetAddon("ShadowUI")
local act = Addon.Defaults.act

Addon.Defaults.classes.WARLOCK = {
  layout = {},
  keybinds = {
    ["CLICK ShadowUIActionButton1:Keybind"] = "Q",
    ["CLICK ShadowUIActionButton2:Keybind"] = "E",
    ["CLICK ShadowUIActionButton3:Keybind"] = "R",
    ["CLICK ShadowUIActionButton4:Keybind"] = "F",
    ["CLICK ShadowUIActionButton5:Keybind"] = "T",
    ["CLICK ShadowUIActionButton6:Keybind"] = "G",
    ["CLICK ShadowUIActionButton7:Keybind"] = "C",
    ["CLICK ShadowUIActionButton8:Keybind"] = "V",
    ["CLICK ShadowUIActionButton9:Keybind"] = "B",
    ["CLICK ShadowUIActionButton10:Keybind"] = "X",
    ["CLICK ShadowUIActionButton11:Keybind"] = "Z",
    ["CLICK ShadowUIActionButton12:Keybind"] = "H",
    ["CLICK ShadowUIActionButton13:Keybind"] = "1",
    ["CLICK ShadowUIActionButton14:Keybind"] = "2",
    ["CLICK ShadowUIActionButton15:Keybind"] = "3",
    ["CLICK ShadowUIActionButton16:Keybind"] = "4",
    ["CLICK ShadowUIActionButton17:Keybind"] = "5",
    ["CLICK ShadowUIActionButton18:Keybind"] = "`",
    ["CLICK ShadowUIActionButton19:Keybind"] = "SHIFT-Q",
    ["CLICK ShadowUIActionButton20:Keybind"] = "SHIFT-E",
    ["CLICK ShadowUIActionButton21:Keybind"] = "SHIFT-R",
    ["CLICK ShadowUIActionButton22:Keybind"] = "SHIFT-F",
    ["CLICK ShadowUIActionButton23:Keybind"] = "SHIFT-T",
    ["CLICK ShadowUIActionButton24:Keybind"] = "N",
    ["CLICK ShadowUIActionButton25:Keybind"] = "SHIFT-G",
    ["CLICK ShadowUIActionButton26:Keybind"] = "SHIFT-C",
    ["CLICK ShadowUIActionButton27:Keybind"] = "SHIFT-V",
    ["CLICK ShadowUIActionButton28:Keybind"] = "SHIFT-B",
    ["CLICK ShadowUIActionButton29:Keybind"] = "SHIFT-X",
    ["CLICK ShadowUIActionButton30:Keybind"] = "SHIFT-Z",
    ["CLICK ShadowUIActionButton31:Keybind"] = "SHIFT-H",
    ["CLICK ShadowUIActionButton32:Keybind"] = "SHIFT-N",
    ["CLICK ShadowUIActionButton33:Keybind"] = "6",
    ["CLICK ShadowUIActionButton34:Keybind"] = "7",
    ["CLICK ShadowUIActionButton35:Keybind"] = "8",
    ["CLICK ShadowUIActionButton36:Keybind"] = "9",
    ["CLICK ShadowUIActionButton37:Keybind"] = "SHIFT-1",
    ["CLICK ShadowUIActionButton38:Keybind"] = "SHIFT-2",
    ["CLICK ShadowUIActionButton39:Keybind"] = "SHIFT-3",
    ["CLICK ShadowUIActionButton40:Keybind"] = "SHIFT-4",
    ["CLICK ShadowUIActionButton41:Keybind"] = "SHIFT-5",
    ["CLICK ShadowUIActionButton42:Keybind"] = "SHIFT-`",
    ["CLICK ShadowUIActionButton43:Keybind"] = "ALT-1",
    ["CLICK ShadowUIActionButton44:Keybind"] = "ALT-2",
    ["CLICK ShadowUIActionButton45:Keybind"] = "ALT-3",
    ["CLICK ShadowUIActionButton46:Keybind"] = "ALT-4",
    ["CLICK ShadowUIActionButton47:Keybind"] = "ALT-5",
    ["CLICK ShadowUIActionButton48:Keybind"] = "ALT-6",
    ["CLICK ShadowUIActionButton49:Keybind"] = "ALT-Q",
    ["CLICK ShadowUIActionButton50:Keybind"] = "ALT-E",
    ["CLICK ShadowUIActionButton51:Keybind"] = "ALT-R",
    ["CLICK ShadowUIActionButton52:Keybind"] = "ALT-F",
    ["CLICK ShadowUIActionButton53:Keybind"] = "ALT-T",
    ["CLICK ShadowUIActionButton54:Keybind"] = "ALT-G",
    ["CLICK ShadowUIActionButton55:Keybind"] = "ALT-C",
    ["CLICK ShadowUIActionButton56:Keybind"] = "ALT-V",
    ["CLICK ShadowUIActionButton57:Keybind"] = "ALT-B",
    ["CLICK ShadowUIActionButton58:Keybind"] = "ALT-X",
    ["CLICK ShadowUIActionButton59:Keybind"] = "ALT-Z",
    ["CLICK ShadowUIActionButton60:Keybind"] = "0",
    ["CLICK ShadowUIActionButton61:Keybind"] = "CTRL-Q",
    ["CLICK ShadowUIActionButton62:Keybind"] = "CTRL-E",
    ["CLICK ShadowUIActionButton63:Keybind"] = "CTRL-R",
    ["CLICK ShadowUIActionButton64:Keybind"] = "CTRL-F",
    ["CLICK ShadowUIActionButton65:Keybind"] = "CTRL-T",
    ["CLICK ShadowUIActionButton66:Keybind"] = "CTRL-G",
    ["CLICK ShadowUIActionButton67:Keybind"] = "CTRL-C",
    ["CLICK ShadowUIActionButton68:Keybind"] = "CTRL-V",
    ["CLICK ShadowUIActionButton69:Keybind"] = "CTRL-B",
    ["CLICK ShadowUIActionButton70:Keybind"] = "CTRL-1",
    ["CLICK ShadowUIActionButton71:Keybind"] = "CTRL-2",
    ["CLICK ShadowUIActionButton72:Keybind"] = "CTRL-3",
    ["CLICK ShadowUIActionButton73:Keybind"] = "BUTTON5",
    ["CLICK ShadowUIActionButton74:Keybind"] = "BUTTON4",
    ["CLICK ShadowUIActionButton75:Keybind"] = "BUTTON3",
    ["CLICK ShadowUIActionButton76:Keybind"] = "ALT-SHIFT-1",
    ["CLICK ShadowUIActionButton77:Keybind"] = "ALT-SHIFT-2",
    ["CLICK ShadowUIActionButton78:Keybind"] = "ALT-SHIFT-3",
    ["CLICK ShadowUIActionButton79:Keybind"] = "F1",
    ["CLICK ShadowUIActionButton80:Keybind"] = "ALT-SHIFT-Q",
    ["CLICK ShadowUIActionButton81:Keybind"] = "ALT-SHIFT-E",
    ["CLICK ShadowUIActionButton82:Keybind"] = "ALT-SHIFT-R",
    ["CLICK ShadowUIActionButton83:Keybind"] = "ALT-SHIFT-F",
    ["CLICK ShadowUIActionButton84:Keybind"] = "ALT-SHIFT-C",
  },
  actions = {
    [1] = act("l-sb", "sbolt", { match = "sbolt" }),
    [2] = act("l-corr", "corr", { match = "corr" }),
    [3] = act("l-coa", "coa", { match = "coa" }),
    [4] = act("l-lock", "lock", { match = "Spell Lock" }),
    [5] = act("shared-t13", "t13", { match = "t13" }),
    [7] = act("l-fear", "fear", { match = "fear" }),
    [8] = act("l-drain", "drain", { match = "drain" }),
    [9] = act("l-howl", "howl", { match = "howl" }),
    [10] = act("l-banish", "ban", { match = "Banish" }),
    [11] = act("l-coil", "dc", { match = "Death Coil" }),
    [12] = act("l-armor", "da", { match = "Demon Armor" }),
    [13] = act("l-tap", "lt", { match = "lt" }),
    [14] = act("l-imm", "imm", { match = "Immolate" }),
    [15] = act("l-shadowburn", "sbn", { match = "Shadowburn" }),
    [16] = act("l-wand", "lwand", { match = "Shoot" }),
    [17] = act("l-dlife", "dlife", { match = "dlife" }),
    [18] = act("shared-pa", "pa", { match = "pa" }),
    [19] = act("spell:603", "Curse of Doom", {
      kind = "spell",
      spellId = 603,
    }),
    [20] = act("l-cor", "cor", { match = "cor" }),
    [21] = act("l-cosh", "cosh", { match = "cosh" }),
    [22] = act("l-cot", "cot", { match = "cot" }),
    [23] = act("l-cowk", "cowk", { match = "cowk" }),
    [24] = act("l-sum", "sum", { match = "sum" }),
    [25] = act("l-dmana", "dmana", { match = "dmana" }),
    [26] = act("spell:17951", "Create Firestone", {
      kind = "spell",
      spellId = 17951,
    }),
    [27] = act("spell:17952", "Create Firestone (Greater)", {
      kind = "spell",
      spellId = 17952,
    }),
    [28] = act("spell:6366", "Create Firestone (Lesser)", {
      kind = "spell",
      spellId = 6366,
    }),
    [29] = act("spell:17953", "Create Firestone (Major)", {
      kind = "spell",
      spellId = 17953,
    }),
    [30] = act("l-sac", "sac", { match = "Sacrifice" }),
    [31] = act("spell:5699", "Create Healthstone", {
      kind = "spell",
      spellId = 5699,
    }),
    [32] = act("spell:11729", "Create Healthstone (Greater)", {
      kind = "spell",
      spellId = 11729,
    }),
    [33] = act("l-ss", "soulstone", { match = "Major Soulstone" }),
    [34] = act("l-fel", "fel", { match = "fel" }),
    [35] = act("spell:6202", "Create Healthstone (Lesser)", {
      kind = "spell",
      spellId = 6202,
    }),
    [36] = act("spell:11730", "Create Healthstone (Major)", {
      kind = "spell",
      spellId = 11730,
    }),
    [37] = act("spell:6201", "Create Healthstone (Minor)", {
      kind = "spell",
      spellId = 6201,
    }),
    [38] = act("spell:20755", "Create Soulstone", {
      kind = "spell",
      spellId = 20755,
    }),
    [39] = act("spell:20756", "Create Soulstone (Greater)", {
      kind = "spell",
      spellId = 20756,
    }),
    [40] = act("spell:20752", "Create Soulstone (Lesser)", {
      kind = "spell",
      spellId = 20752,
    }),
    [41] = act("spell:20757", "Create Soulstone (Major)", {
      kind = "spell",
      spellId = 20757,
    }),
    [42] = act("shared-pf", "pf", { match = "pf" }),
    [43] = act("spell:693", "Create Soulstone (Minor)", {
      kind = "spell",
      spellId = 693,
    }),
    [44] = act("spell:2362", "Create Spellstone", {
      kind = "spell",
      spellId = 2362,
    }),
    [45] = act("spell:17727", "Create Spellstone (Greater)", {
      kind = "spell",
      spellId = 17727,
    }),
    [46] = act("spell:17728", "Create Spellstone (Major)", {
      kind = "spell",
      spellId = 17728,
    }),
    [47] = act("l-dskin", "dskin", { match = "dskin" }),
    [48] = act("spell:11743", "Detect Greater Invisibility", {
      kind = "spell",
      spellId = 11743,
    }),
    [49] = act("spell:2970", "Detect Invisibility", {
      kind = "spell",
      spellId = 2970,
    }),
    [50] = act("spell:132", "Detect Lesser Invisibility", {
      kind = "spell",
      spellId = 132,
    }),
    [51] = act("spell:126", "Eye of Kilrogg", {
      kind = "spell",
      spellId = 126,
    }),
    [52] = act("l-hfunnel", "hfunnel", { match = "hfunnel" }),
    [53] = act("spell:1122", "Inferno", {
      kind = "spell",
      spellId = 1122,
    }),
    [54] = act("spell:18540", "Ritual of Doom", {
      kind = "spell",
      spellId = 18540,
    }),
    [55] = act("spell:5500", "Sense Demons", {
      kind = "spell",
      spellId = 5500,
    }),
    [56] = act("l-sward", "sward", { match = "sward" }),
    [57] = act("l-subj", "subj", { match = "subj" }),
    [58] = act("spell:23161", "Summon Dreadsteed", {
      kind = "spell",
      spellId = 23161,
    }),
    [59] = act("spell:5784", "Summon Felsteed", {
      kind = "spell",
      spellId = 5784,
    }),
    [60] = act("spell:688", "Summon Imp", {
      kind = "spell",
      spellId = 688,
    }),
    [61] = act("spell:713", "Summon Incubus", {
      kind = "spell",
      spellId = 713,
    }),
    [62] = act("spell:697", "Summon Voidwalker", {
      kind = "spell",
      spellId = 697,
    }),
    [63] = act("spell:5697", "Unending Breath", {
      kind = "spell",
      spellId = 5697,
    }),
    [64] = act("l-hell", "hell", { match = "hell" }),
    [65] = act("l-rof", "rof", { match = "rof" }),
    [66] = act("l-spain", "spain", { match = "spain" }),
    [67] = act("l-sfire", "sfire", { match = "sfire" }),
    [74] = act("l-tap", "lt", { match = "lt" }),
  },
}
